<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enable Mobile Notification- No</name>
   <tag></tag>
   <elementGuidId>4a18e3d4-7d7d-4bb7-b80f-2cab803c94c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_rbtnMobNotofication_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_rbtnMobNotofication_1']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_rbtnMobNotofication_1]</value>
   </webElementProperties>
</WebElementEntity>
